"""
Project Specification Schema — Level 0 Foundation

Defines the architecture output schema generated by architect_agent.
Immutable after Step 0 human review.
"""
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class ModuleType(str, Enum):
    """UE5 module types."""
    CORE = "Core"
    GAME_FRAMEWORK = "GameFramework"
    GENRE_SYSTEM = "GenreSystem"
    UI = "UI"
    PLATFORM = "Platform"


class SubsystemRef(str, Enum):
    """UE5 subsystem references."""
    GAS = "GameplayAbilitySystem"
    ENHANCED_INPUT = "EnhancedInput"
    WORLD_PARTITION = "WorldPartition"
    LEVEL_STREAMING = "LevelStreaming"
    ONLINE_SUBSYSTEM = "OnlineSubsystem"
    REPLICATION = "Replication"
    REDUCED_TICK = "ReducedTick"
    AGGRESSIVE_LOD = "AggressiveLOD"
    CUSTOM_STATE_MACHINE = "CustomStateMachine"


class ModuleSpec(BaseModel):
    """Specification for a UE5 module."""
    module_name: str
    module_type: ModuleType
    dependencies: List[str]
    public_include_paths: List[str] = []
    private_include_paths: List[str] = []
    dependency_modules: List[str] = []
    b_force_compile: bool = False
    platform_guards: List[str] = []


class Pattern(BaseModel):
    """Learning store pattern schema."""
    pattern_id: str
    genre: str
    system_type: str
    cpp_templates: List[str] = []
    blueprint_templates: List[str] = []
    ubt_module_config: Optional[Dict] = None
    common_errors: List[str] = []
    repair_strategies: List[str] = []
    success_rate: float = 0.0
    avg_repair_cycles: int = 0


class ProjectSpec(BaseModel):
    """
    Complete project architecture specification.
    
    Generated by architect_agent from GameBrief.
    """
    project_id: str
    project_name: str
    modules: List[ModuleSpec]
    subsystems: List[SubsystemRef]
    cpp_files: List[str]
    blueprint_files: List[str]
    ubt_module_deps: Dict[str, List[str]]
    platform_targets: List[str]
    estimated_compile_min: int
    genre_patterns: List[str] = []
