"""
Project Specification Schema — Level 0 Foundation

Defines the architecture output schema generated by architect_agent.
Immutable after Step 0 human review.

Dependencies:
- contracts.models.game_brief (Genre, Platform)
- contracts.models.build_result (TestSpec)
"""
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, field_validator

from contracts.models.game_brief import Genre, Platform
from contracts.models.build_result import TestSpec


class ModuleType(str, Enum):
    """
    UE5 module types.
    
    Defines the module hierarchy for UBT dependency graph.
    """
    CORE = "Core"
    GAME_FRAMEWORK = "GameFramework"
    GENRE_SYSTEM = "GenreSystem"
    UI = "UI"
    PLATFORM = "Platform"


class SubsystemRef(str, Enum):
    """
    UE5 subsystem references.
    
    Selected by architect_agent based on game genre.
    """
    GAS = "GameplayAbilitySystem"
    ENHANCED_INPUT = "EnhancedInput"
    WORLD_PARTITION = "WorldPartition"
    LEVEL_STREAMING = "LevelStreaming"
    ONLINE_SUBSYSTEM = "OnlineSubsystem"
    REPLICATION = "Replication"
    REDUCED_TICK = "ReducedTick"
    AGGRESSIVE_LOD = "AggressiveLOD"
    CUSTOM_STATE_MACHINE = "CustomStateMachine"


class ModuleSpec(BaseModel):
    """
    Specification for a UE5 module.
    
    Attributes:
        module_name: Module name (e.g., "MyGameCore")
        module_type: Type of module (Core, GameFramework, etc.)
        dependencies: List of module dependencies
        public_include_paths: Public include paths
        private_include_paths: Private include paths
        dependency_modules: UE5 dependency modules (Engine, CoreUObject, etc.)
        b_force_compile: Force compilation flag
        platform_guards: Platform guard list
    """
    module_name: str
    module_type: ModuleType
    dependencies: List[str] = Field(default_factory=list)
    public_include_paths: List[str] = Field(default_factory=list)
    private_include_paths: List[str] = Field(default_factory=list)
    dependency_modules: List[str] = Field(default_factory=list)
    b_force_compile: bool = False
    platform_guards: List[str] = Field(default_factory=list)
    
    @field_validator('module_name')
    @classmethod
    def module_name_not_empty(cls, v: str) -> str:
        """Validate module_name is not empty."""
        if not v or not v.strip():
            raise ValueError('module_name cannot be empty')
        return v.strip()


class Pattern(BaseModel):
    """
    Learning store pattern schema.
    
    Attributes:
        pattern_id: Unique pattern identifier
        genre: Game genre this pattern applies to
        system_type: System type (e.g., "Inventory", "Combat")
        cpp_templates: List of C++ template file paths
        blueprint_templates: List of Blueprint template file paths
        ubt_module_config: UBT module configuration
        common_errors: List of common error patterns
        repair_strategies: List of repair strategies
        success_rate: Pattern success rate (0.0-1.0)
        avg_repair_cycles: Average repair cycles for this pattern
    """
    pattern_id: str
    genre: str
    system_type: str
    cpp_templates: List[str] = Field(default_factory=list)
    blueprint_templates: List[str] = Field(default_factory=list)
    ubt_module_config: Optional[Dict[str, Any]] = None
    common_errors: List[str] = Field(default_factory=list)
    repair_strategies: List[str] = Field(default_factory=list)
    success_rate: float = 0.0
    avg_repair_cycles: int = 0
    
    @field_validator('pattern_id')
    @classmethod
    def pattern_id_not_empty(cls, v: str) -> str:
        """Validate pattern_id is not empty."""
        if not v or not v.strip():
            raise ValueError('pattern_id cannot be empty')
        return v.strip()
    
    @field_validator('genre')
    @classmethod
    def genre_not_empty(cls, v: str) -> str:
        """Validate genre is not empty."""
        if not v or not v.strip():
            raise ValueError('genre cannot be empty')
        return v.strip()
    
    @field_validator('system_type')
    @classmethod
    def system_type_not_empty(cls, v: str) -> str:
        """Validate system_type is not empty."""
        if not v or not v.strip():
            raise ValueError('system_type cannot be empty')
        return v.strip()
    
    @field_validator('success_rate')
    @classmethod
    def success_rate_valid(cls, v: float) -> float:
        """Validate success_rate is between 0 and 1."""
        if v < 0 or v > 1:
            raise ValueError('success_rate must be between 0 and 1')
        return v
    
    @field_validator('avg_repair_cycles')
    @classmethod
    def repair_cycles_non_negative(cls, v: int) -> int:
        """Validate avg_repair_cycles is non-negative."""
        if v < 0:
            raise ValueError('avg_repair_cycles must be non-negative')
        return v


class ProjectSpec(BaseModel):
    """
    Complete project architecture specification.
    
    Generated by architect_agent from GameBrief.
    
    Attributes:
        project_id: Unique project identifier
        project_name: Project name
        modules: List of module specifications
        subsystems: List of UE5 subsystem references
        cpp_files: List of C++ files to generate
        blueprint_files: List of Blueprint files to generate
        ubt_module_deps: UBT module dependency graph
        platform_targets: List of target platforms
        estimated_compile_min: Estimated compile time in minutes
        genre_patterns: List of genre-specific patterns
    """
    project_id: str
    project_name: str
    modules: List[ModuleSpec] = Field(default_factory=list)
    subsystems: List[SubsystemRef] = Field(default_factory=list)
    cpp_files: List[str] = Field(default_factory=list)
    blueprint_files: List[str] = Field(default_factory=list)
    ubt_module_deps: Dict[str, List[str]] = Field(default_factory=dict)
    platform_targets: List[str] = Field(default_factory=list)
    estimated_compile_min: int = 5
    genre_patterns: List[str] = Field(default_factory=list)
    
    @field_validator('project_id')
    @classmethod
    def project_id_not_empty(cls, v: str) -> str:
        """Validate project_id is not empty."""
        if not v or not v.strip():
            raise ValueError('project_id cannot be empty')
        return v.strip()
    
    @field_validator('project_name')
    @classmethod
    def project_name_not_empty(cls, v: str) -> str:
        """Validate project_name is not empty."""
        if not v or not v.strip():
            raise ValueError('project_name cannot be empty')
        return v.strip()
    
    @field_validator('estimated_compile_min')
    @classmethod
    def compile_time_positive(cls, v: int) -> int:
        """Validate estimated_compile_min is positive."""
        if v <= 0:
            raise ValueError('estimated_compile_min must be positive')
        return v
    
    @field_validator('platform_targets')
    @classmethod
    def at_least_one_target(cls, v: List[str]) -> List[str]:
        """Validate at least one platform target."""
        if not v or len(v) == 0:
            raise ValueError('at least one platform target must be specified')
        return v
